language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      branches:
        only:
          - master
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - C_COMPILER=gcc-4.9
        - CXX_COMPILER=g++-4.9
    - os: linux
      dist: trusty
      compiler: gcc
      branches:
        only:
          - master
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - C_COMPILER=gcc-5
        - CXX_COMPILER=g++-5
    - os: linux
      dist: trusty
      compiler: gcc
      branches:
        only:
          - master
          - testing
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - C_COMPILER=gcc-6
        - CXX_COMPILER=g++-6
    - os: linux
      dist: trusty
      compiler: clang
      branches:
        only:
          - master
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.5 main"
          packages:
            - g++-4.9
            - clang-3.5
      env:
        - C_COMPILER=clang-3.5
        - CXX_COMPILER=clang++-3.5
    - os: linux
      dist: trusty
      compiler: clang
      branches:
        only:
          - master
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.6 main"
          packages:
            - g++-4.9
            - clang-3.6
      env:
        - C_COMPILER=clang-3.6
        - CXX_COMPILER=clang++-3.6

before_install:  # necessary because Travis overwrites CXX and CC!
  - if [[ $TRAVIS_OS_NAME == linux ]]; then export CXX=$CXX_COMPILER CC=$C_COMPILER; fi

install:
  - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo apt-get install qt5-default; fi #install Qt5 libraries
  - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo bash ./install-linux-deps.sh; fi  # Why do I need permission?

  # install tinyxml2
  - git clone https://github.com/leethomason/tinyxml2.git
  - cd tinyxml2
  - cmake . -DBUILD_SHARED_LIBS:BOOL=OFF -DBUILD_STATIC_LIBS:BOOL=ON -DCMAKE_CXX_FLAGS=-fPIC && sudo make install

  # install and build Elpp
  - cd $TRAVIS_BUILD_DIR
  # creating a dir to clone and build Elpp (Created due to name conflict with original folder "easyloggingpp"
  - mkdir temp_elpp
  - cd temp_elpp
  - git clone https://github.com/muflihun/easyloggingpp.git
  - mv $TRAVIS_BUILD_DIR/easyloggingpp/CMakeLists.txt $TRAVIS_BUILD_DIR/temp_elpp/easyloggingpp
  - cd easyloggingpp
  - mkdir build 
  - cd build
  - cmake ..
  - cmake --build .
  - sudo make install 
  - cd $TRAVIS_BUILD_DIR

before_script:
#Set the script to execute
  - chmod a+x reconfig.sh
  - chmod a+x KTAB_Test_Apps.sh
  - chmod a+x ./examples/smp/SMPC_RefRuns_Compare.sh

script:
  - ./reconfig.sh

after_success:
  - ./KTAB_Test_Apps_Travis.sh > ./ktab.log
  - cd $TRAVIS_BUILD_DIR/examples/smp
  - ./SMPC_RefRuns_Compare.sh > ./smp.log
  - cat ../../ktab.log
  - cat ./smp.log
